import { createHash } from "node:crypto";
import { getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { API_ORGANIZATION_ID, getAdminApp } from "./apiAuth.js";

export const acceptanceUsers = [
  ["accept_admin", "admin"], ["accept_owner", "project_manager"], ["accept_lead", "project_manager"],
  ["accept_contributor", "contributor"], ["accept_viewer", "viewer"], ["accept_client", "client"]
];
export const acceptancePassword = "Lifecycle-Acceptance-2026!";
export const acceptanceProjectId = "accept_project_active";

const activeLifecycle = { schemaVersion: 1, state: "active", retentionClass: "ordinary_project", legalHold: false, lastOperationId: "fixture_seed" };
const trashedLifecycle = { schemaVersion: 1, state: "trashed", retentionClass: "operational_30d", legalHold: false, lastOperationId: "fixture_trash", purgeEligibleAt: "2026-01-01T00:00:00.000Z", trashed: { at: "2025-12-01T00:00:00.000Z", by: "accept_admin", reason: { code: "fixture" }, restoreDeadline: "2026-01-01T00:00:00.000Z" } };

export async function seedLifecycleAcceptanceFixtures({ database = getFirestore(getAdminApp()), bucket = getStorage(getAdminApp()).bucket(process.env.FIREBASE_STORAGE_BUCKET || "accelprojects-acceptance.appspot.com") } = {}) {
  const organization = database.doc(`organizations/${API_ORGANIZATION_ID}`);
  await database.recursiveDelete(organization).catch(() => undefined);
  await organization.set({ id: API_ORGANIZATION_ID, name: "AccelProjects Acceptance", slug: "accelprojects-acceptance", createdAt: "2026-01-01T00:00:00.000Z" });
  const batch = database.batch();
  for (const [id, role] of acceptanceUsers) batch.set(organization.collection("users").doc(id), { id, organizationId: API_ORGANIZATION_ID, name: id, email: `${id}@example.test`, avatarInitials: "AT", role, createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z" });
  batch.set(organization.collection("clients").doc("accept_client_record"), { id: "accept_client_record", organizationId: API_ORGANIZATION_ID, name: "Acceptance Client", contactName: "Acceptance Contact", email: "client@example.test", phone: "555-0100", status: "active", lifecycle: activeLifecycle });
  const projects = [
    [acceptanceProjectId, "active", activeLifecycle],
    ["accept_project_archived", "archived", { ...activeLifecycle, state: "archived", lastOperationId: "fixture_archive" }],
    ["accept_project_trashed", "active", trashedLifecycle]
  ];
  for (const [id, status, lifecycle] of projects) batch.set(organization.collection("projects").doc(id), { id, organizationId: API_ORGANIZATION_ID, clientId: "accept_client_record", ownerId: "accept_owner", name: id, summary: "Lifecycle acceptance fixture", status, health: "on_track", priority: "medium", startDate: "2026-01-01", targetDate: "2026-12-31", budget: 1000, currency: "USD", revision: 1, updatedAt: "2026-01-01T00:00:00.000Z", lastStructuralChangeAt: "2026-01-01T00:00:00.000Z", lifecycle });
  const project = organization.collection("projects").doc(acceptanceProjectId);
  batch.set(organization.collection("portalUsers").doc("accept_client"), { id: "accept_client", organizationId: API_ORGANIZATION_ID, userId: "accept_client", clientId: "accept_client_record", email: "accept_client@example.test", displayName: "Acceptance Client User", status: "active", createdBy: "accept_admin", createdAt: "2026-01-01T00:00:00.000Z", updatedBy: "accept_admin", updatedAt: "2026-01-01T00:00:00.000Z", lastPortalLoginAt: null, revokedBy: null });
  batch.set(organization.collection("portalUsers").doc("accept_client").collection("projectAccess").doc(acceptanceProjectId), { id: acceptanceProjectId, organizationId: API_ORGANIZATION_ID, userId: "accept_client", clientId: "accept_client_record", projectId: acceptanceProjectId, status: "active", accessLevel: "read_only", expiresAt: null, createdBy: "accept_admin", createdAt: "2026-01-01T00:00:00.000Z", updatedBy: "accept_admin", updatedAt: "2026-01-01T00:00:00.000Z" });
  batch.set(organization.collection("portalProjects").doc(acceptanceProjectId), { id: acceptanceProjectId, organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, clientId: "accept_client_record", projectName: "accept_project_active", clientName: "Acceptance Client", clientFacingSummary: "Lifecycle acceptance fixture", health: "on_track", progressPercent: 25, targetDate: "2026-12-31", currentPhaseLabel: "Discovery", statusNarrative: "On track", nextUpdateExpectedAt: "2026-02-15", projectManagerName: "accept_owner", projectManagerEmail: "accept_owner@example.test", projectManagerPhone: "", latestPublishedReportSnapshotId: "snapshot_1", publicationStatus: "published", visibility: "client_visible", publishedAt: "2026-01-01T03:00:00.000Z", updatedAt: "2026-01-01T03:00:00.000Z" });
  for (const [id, role] of [["accept_lead", "lead"], ["accept_contributor", "contributor"], ["accept_viewer", "observer"]]) batch.set(project.collection("members").doc(id), { id, projectId: acceptanceProjectId, userId: id, role, accessState: "active", lifecycle: activeLifecycle });
  for (const [id, name] of [["phase_1", "Discovery"], ["phase_2", "Delivery"]]) batch.set(project.collection("phases").doc(id), { id, projectId: acceptanceProjectId, name, status: "active", startDate: "2026-01-01", endDate: "2026-06-01", lifecycle: activeLifecycle });
  for (const [id, phaseId] of [["task_1", "phase_1"], ["task_2", "phase_1"], ["task_3", "phase_2"]]) batch.set(project.collection("tasks").doc(id), { id, projectId: acceptanceProjectId, phaseId, title: id, description: "Acceptance task", status: "todo", priority: "medium", assigneeId: "accept_contributor", startDate: "2026-02-01", dueDate: "2026-02-10", lifecycle: activeLifecycle });
  batch.set(project.collection("taskDependencies").doc("dep_1_2"), { id: "dep_1_2", projectId: acceptanceProjectId, taskId: "task_2", dependsOnTaskId: "task_1", type: "finish_to_start", lagDays: 0, lifecycle: activeLifecycle });
  batch.set(project.collection("tasks").doc("task_1").collection("comments").doc("comment_1"), { id: "comment_1", taskId: "task_1", authorId: "accept_contributor", body: "Retained comment", visibility: "internal", createdAt: "2026-01-01T00:00:00.000Z", revision: 1 });
  batch.set(project.collection("milestones").doc("milestone_1"), { id: "milestone_1", projectId: acceptanceProjectId, name: "Acceptance milestone", date: "2026-03-01", status: "planned", lifecycle: activeLifecycle });
  batch.set(project.collection("risks").doc("risk_1"), { id: "risk_1", projectId: acceptanceProjectId, title: "Acceptance risk", status: "open", severity: "high", probability: "medium", lifecycle: activeLifecycle });
  batch.set(project.collection("metrics").doc("metric_manual"), { id: "metric_manual", projectId: acceptanceProjectId, label: "Manual", value: 1, source: "manual", lifecycle: activeLifecycle });
  batch.set(project.collection("metrics").doc("metric_computed"), { id: "metric_computed", projectId: acceptanceProjectId, label: "Computed", value: 2, source: "computed", lifecycle: activeLifecycle });
  batch.set(project.collection("documents").doc("document_external"), { id: "document_external", projectId: acceptanceProjectId, title: "External link", type: "other", managed: false, url: "https://example.test/document", lifecycle: activeLifecycle });
  const content = Buffer.from("acceptance managed document"); const storagePath = `organizations/${API_ORGANIZATION_ID}/projects/${acceptanceProjectId}/documents/document_managed/versions/version_1/acceptance.txt`; const digest = createHash("sha256").update(content).digest("hex");
  batch.set(project.collection("documents").doc("document_managed"), { id: "document_managed", projectId: acceptanceProjectId, title: "Managed", type: "other", category: "general", managed: true, storageProvider: "firebase_storage", currentVersionId: "version_1", lifecycle: activeLifecycle });
  batch.set(project.collection("documents").doc("document_managed").collection("versions").doc("version_1"), { id: "version_1", projectId: acceptanceProjectId, documentId: "document_managed", storagePath, checksumSha256: digest, contentType: "text/plain", sizeBytes: content.length, createdAt: "2026-01-01T00:00:00.000Z" });
  const communicationBase = { organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, channel: "email", direction: "outbound", audience: "client", visibility: "internal", bodyText: "Acceptance update", toRecipients: [{ email: "client@example.test" }], ccRecipients: [], bccRecipients: [], senderMailbox: "sender@example.test", provider: "microsoft_graph", sourceType: "manual_project_update", sourceId: null, attachmentRefs: [], idempotencyKey: "fixture_communication", createdBy: "accept_owner", createdAt: "2026-01-01T00:00:00.000Z", updatedBy: "accept_owner", updatedAt: "2026-01-01T00:00:00.000Z", sendRequestedAt: null, acceptedAt: null, failedAt: null, lastErrorCode: null, lastErrorMessage: null, lifecycle: activeLifecycle };
  batch.set(project.collection("communications").doc("communication_draft"), { ...communicationBase, id: "communication_draft", subject: "Draft", status: "draft", attachmentRefs: [{ documentId: "document_managed" }] });
  batch.set(project.collection("communications").doc("communication_accepted"), { ...communicationBase, id: "communication_accepted", subject: "Accepted", status: "accepted", idempotencyKey: "fixture_accepted", acceptedAt: "2026-01-01T00:01:00.000Z" });
  batch.set(project.collection("communications").doc("communication_accepted").collection("deliveryAttempts").doc("attempt_1"), { id: "attempt_1", status: "accepted", providerMessageId: "fixture", createdAt: "2026-01-01T00:00:00.000Z" });
  const calendarBase = { organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, descriptionText: "Acceptance event", visibility: "internal", calendarOwnerEmail: "calendar@example.test", startDateTime: "2026-03-01T15:00:00", endDateTime: "2026-03-01T16:00:00", timeZone: "Eastern Standard Time", isAllDay: false, location: "", attendees: [{ email: "client@example.test" }], reminderMinutesBeforeStart: 15, relatedEntityType: "project", relatedEntityId: null, transactionId: "fixture_calendar", graphEventId: null, graphICalUId: null, graphWebLink: null, graphChangeKey: null, createdBy: "accept_owner", createdAt: "2026-01-01T00:00:00.000Z", updatedBy: "accept_owner", updatedAt: "2026-01-01T00:00:00.000Z", lastSyncedAt: null, lastErrorCode: null, lastErrorMessage: null, lifecycle: activeLifecycle };
  batch.set(project.collection("calendarEvents").doc("calendar_draft"), { ...calendarBase, id: "calendar_draft", title: "Draft calendar", status: "draft" });
  batch.set(project.collection("calendarEvents").doc("calendar_scheduled"), { ...calendarBase, id: "calendar_scheduled", title: "Scheduled calendar", status: "scheduled", transactionId: "fixture_scheduled", graphEventId: "graph_fixture" });
  const reportBase = { organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, reportingPeriodStart: "2026-01-01", reportingPeriodEnd: "2026-01-31", executiveSummary: "Acceptance summary", progressSummary: "Acceptance progress", nextSteps: "Acceptance next steps", clientActions: [], highlights: [], risks: [], milestones: [], completedTasks: [], upcomingTasks: [{ id: "task_1", title: "task_1", status: "todo", dueDate: "2026-02-10", owner: "accept_contributor" }], includeBudget: false, includeInternalNotes: false, latestApprovedSnapshotId: null, createdBy: "accept_owner", createdAt: "2026-01-01T00:00:00.000Z", updatedBy: "accept_owner", updatedAt: "2026-01-01T00:00:00.000Z", submittedAt: null, submittedBy: null, approvedAt: null, approvedBy: null, lifecycle: activeLifecycle, taskIds: ["task_1"] };
  for (const [id, status] of [["report_draft", "draft"], ["report_submitted", "ready_for_review"], ["report_approved", "approved"], ["report_superseded", "superseded"]]) batch.set(project.collection("reports").doc(id), { ...reportBase, id, title: id, status, latestApprovedSnapshotId: status === "approved" ? "snapshot_1" : null, submittedAt: status === "ready_for_review" ? "2026-01-01T01:00:00.000Z" : null, submittedBy: status === "ready_for_review" ? "accept_owner" : null, approvedAt: status === "approved" ? "2026-01-01T02:00:00.000Z" : null, approvedBy: status === "approved" ? "accept_owner" : null });
  batch.set(project.collection("reports").doc("report_approved").collection("snapshots").doc("snapshot_1"), { id: "snapshot_1", organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, reportId: "report_approved", title: "Approved acceptance report", reportingPeriodStart: "2026-01-01", reportingPeriodEnd: "2026-01-31", project: { id: acceptanceProjectId }, client: { id: "accept_client_record" }, sections: { executiveSummary: "Acceptance", progressSummary: "Progress", nextSteps: "Next", clientActions: [], highlights: [], risks: [], milestones: [], completedTasks: [], upcomingTasks: [] }, contentHash: digest, projectRevisionAtApproval: 1, sourceReportUpdatedAt: "2026-01-01T00:00:00.000Z", approvedBy: "accept_owner", approvedAt: "2026-01-01T02:00:00.000Z", createdAt: "2026-01-01T02:00:00.000Z", taskIds: ["task_1"] });
  batch.set(project.collection("reports").doc("report_approved").collection("artifacts").doc("artifact_1"), { id: "artifact_1", organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, reportId: "report_approved", snapshotId: "snapshot_1", purpose: "download", filename: "acceptance-report.pdf", contentType: "application/pdf", sizeBytes: 100, sha256: digest, createdBy: "accept_owner", createdAt: "2026-01-01T02:00:00.000Z" });
  batch.set(project.collection("reportPublications").doc("snapshot_1"), { id: "snapshot_1", organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, clientId: "accept_client_record", reportId: "report_approved", snapshotId: "snapshot_1", status: "published", sourceReportStatus: "approved", publishedBy: "accept_owner", publishedAt: "2026-01-01T03:00:00.000Z" });
  batch.set(project.collection("versions").doc("version_fixture"), { id: "version_fixture", projectId: acceptanceProjectId, revision: 1, metadata: { taskId: "task_1" }, createdAt: "2026-01-01T00:00:00.000Z" });
  batch.set(project.collection("activityEvents").doc("activity_fixture"), { id: "activity_fixture", projectId: acceptanceProjectId, actorId: "accept_owner", type: "task_updated", message: "Acceptance task updated", metadata: { taskId: "task_1" }, createdAt: "2026-01-01T00:00:00.000Z" });
  batch.set(project.collection("exportSnapshots").doc("export_fixture"), { id: "export_fixture", projectId: acceptanceProjectId, snapshot: { taskIds: ["task_1"] }, createdAt: "2026-01-01T00:00:00.000Z" });
  batch.set(project.collection("updateManifests").doc("update_fixture"), { id: "update_fixture", projectId: acceptanceProjectId, taskIds: ["task_1"] });
  batch.set(project.collection("importManifests").doc("import_fixture"), { id: "import_fixture", projectId: acceptanceProjectId, taskIds: ["task_1"] });
  batch.set(project.collection("risks").doc("risk_held"), { id: "risk_held", projectId: acceptanceProjectId, title: "Held", status: "open", lifecycle: { ...trashedLifecycle, legalHold: true } });
  batch.set(organization.collection("recordLifecycleOperations").doc("fixture_operation"), { id: "fixture_operation", entityType: "task", entityId: "task_fixture", action: "trash", status: "applied", requestedAt: "2026-01-01T00:00:00.000Z" });
  batch.set(organization.collection("lifecyclePurgeJobs").doc("fixture_purge"), { id: "fixture_purge", entityType: "risk", entityId: "risk_1", state: "planned", requestedAt: "2026-01-01T00:00:00.000Z" });
  await batch.commit();
  await bucket.file(storagePath).save(content, { resumable: false, contentType: "text/plain", metadata: { metadata: { organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, documentId: "document_managed", versionId: "version_1", checksumSha256: digest } } });
  return { organizationId: API_ORGANIZATION_ID, projectId: acceptanceProjectId, storagePath };
}
