import { createHash, randomUUID } from "node:crypto";
import { getFirestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { API_ORGANIZATION_ID, getAdminApp } from "./apiAuth.js";
import { deleteManagedDocumentObjects } from "./documentService.js";

const dbDefault = () => getFirestore(getAdminApp());
const collections = { project: null, projectMember: "members", taskDependency: "taskDependencies", document: "documents", task: "tasks", phase: "phases", milestone: "milestones", risk: "risks", metric: "metrics", report: "reports", communication: "communications", calendarEvent: "calendarEvents" };
const targetRef = (db, input) => input.entityType === "client" ? db.doc(`organizations/${API_ORGANIZATION_ID}/clients/${input.entityId}`) : collections[input.entityType] === null ? db.doc(`organizations/${API_ORGANIZATION_ID}/projects/${input.projectId}`) : db.doc(`organizations/${API_ORGANIZATION_ID}/projects/${input.projectId}/${collections[input.entityType]}/${input.entityId}`);
const operationId = (key) => `lifecycle_${createHash("sha256").update(`${API_ORGANIZATION_ID}:${key}`).digest("hex").slice(0, 32)}`;
export class LifecycleAdminError extends Error { constructor(code, status = 400) { super(code); this.code = code; this.status = status; } }

export async function setLegalHold(input, actor, { database = dbDefault(), now = new Date() } = {}) {
  if (!input.reason?.trim()) throw new LifecycleAdminError("legal_hold_reason_required"); const ref = targetRef(database, input); const id = operationId(input.idempotencyKey); const opRef = database.doc(`organizations/${API_ORGANIZATION_ID}/recordLifecycleOperations/${id}`); let result;
  await database.runTransaction(async (transaction) => { const [existing, snapshot] = await Promise.all([transaction.get(opRef), transaction.get(ref)]); if (existing.exists) { result = existing.data(); return; } if (!snapshot.exists) throw new LifecycleAdminError("record_not_found", 404); const record = snapshot.data(); const timestamp = now.toISOString(); const hold = input.hold === true; const lifecycle = { schemaVersion: 1, state: record.lifecycle?.state || "active", retentionClass: record.lifecycle?.retentionClass || "ordinary_project", ...record.lifecycle, legalHold: hold, lastOperationId: id, legalHoldChangedAt: timestamp, legalHoldChangedBy: actor.uid }; const operation = { id, idempotencyKey: input.idempotencyKey, organizationId: API_ORGANIZATION_ID, projectId: input.projectId || null, entityType: input.entityType, entityId: input.entityId, entityDisplayLabel: record.name || record.title || input.entityId, action: hold ? "legal_hold_set" : "legal_hold_released", actor: { id: actor.uid, role: "admin" }, reason: { code: "legal_hold", note: input.reason.trim().slice(0, 500) }, requestedAt: timestamp, appliedAt: timestamp, priorState: record.lifecycle?.state || "active", resultingState: record.lifecycle?.state || "active", impactCounts: {}, status: "applied", immutableHistoryRetained: true }; transaction.update(ref, { lifecycle }); transaction.create(opRef, operation); result = operation; }); return result;
}

export async function createPurgeJob(input, actor, { database = dbDefault(), now = new Date() } = {}) {
  const id = `purge_${createHash("sha256").update(`${API_ORGANIZATION_ID}:${input.idempotencyKey}`).digest("hex").slice(0, 32)}`; const ref = database.doc(`organizations/${API_ORGANIZATION_ID}/lifecyclePurgeJobs/${id}`); const existing = await ref.get(); if (existing.exists) return existing.data(); const target = await targetRef(database, input).get(); if (!target.exists) throw new LifecycleAdminError("record_not_found", 404); const record = target.data(); if (record.lifecycle?.legalHold) throw new LifecycleAdminError("legal_hold", 409); if (!record.lifecycle?.purgeEligibleAt || Date.parse(record.lifecycle.purgeEligibleAt) > now.getTime()) throw new LifecycleAdminError("retention_not_satisfied", 409); if (input.entityType === "report" && record.latestApprovedSnapshotId) throw new LifecycleAdminError("approved_report_immutable", 409); if (input.entityType === "document" && (record.locked || ["contract", "billing", "approved_deliverable", "report_artifact"].includes(record.category) || record.type === "contract")) throw new LifecycleAdminError("protected_document_retention", 409); if (input.entityType === "communication" && !["draft", "failed"].includes(record.status)) throw new LifecycleAdminError("communication_history_retained", 409); if (input.entityType === "calendarEvent" && (record.graphEventId || ["creating", "updating", "canceling"].includes(record.status))) throw new LifecycleAdminError("calendar_provider_state_retained", 409); const job = { id, organizationId: API_ORGANIZATION_ID, projectId: input.projectId || null, entityType: input.entityType, entityId: input.entityId, idempotencyKey: input.idempotencyKey, requestedBy: actor.uid, requestedAt: now.toISOString(), state: "planned", stage: "reversible", progress: { completed: 0, total: 2 }, errors: [], retainedCopies: ["recordLifecycleOperations", "approvedReportSnapshots", "projectExportSnapshots"], semantics: "operational_purge" }; await ref.create(job); return job;
}

export async function runPurgeJob(jobId, { database = dbDefault() } = {}) {
  const ref = database.doc(`organizations/${API_ORGANIZATION_ID}/lifecyclePurgeJobs/${jobId}`); const snapshot = await ref.get(); if (!snapshot.exists) throw new LifecycleAdminError("purge_job_not_found", 404); let job = snapshot.data(); if (job.state === "completed") return job;
  try { await ref.update({ state: "running", stage: "deleting_storage", updatedAt: new Date().toISOString() }); if (job.entityType === "document") { const target = await targetRef(database, job).get(); if (target.exists && target.data().managed) { const results = await deleteManagedDocumentObjects(job.projectId, job.entityId, { database }); const failed = results.filter((item) => !item.deleted); if (failed.length) throw new LifecycleAdminError("storage_cleanup_incomplete", 409); } } await ref.update({ stage: "deleting_metadata", progress: { completed: 1, total: 2 } }); const target = targetRef(database, job); await database.recursiveDelete(target); const completedAt = new Date().toISOString(); await database.doc(`organizations/${API_ORGANIZATION_ID}/recordLifecycleOperations/purge_${job.id}`).set({ id: `purge_${job.id}`, idempotencyKey: job.idempotencyKey, organizationId: API_ORGANIZATION_ID, projectId: job.projectId, entityType: job.entityType, entityId: job.entityId, entityDisplayLabel: job.entityId, action: "purge", actor: { id: job.requestedBy, role: "admin" }, reason: { code: "operational_purge" }, requestedAt: job.requestedAt, appliedAt: completedAt, priorState: "trashed", resultingState: "purged", impactCounts: {}, status: "applied", immutableHistoryRetained: true, retainedCopies: job.retainedCopies, semantics: "operational_purge" }); await ref.update({ state: "completed", stage: "irreversible_complete", completedAt, progress: { completed: 2, total: 2 } }); job = { ...job, state: "completed", stage: "irreversible_complete", progress: { completed: 2, total: 2 } }; return job; } catch (error) { const safe = error instanceof LifecycleAdminError ? error.code : "purge_failed"; await ref.update({ state: "failed", updatedAt: new Date().toISOString(), errors: [{ code: safe, at: new Date().toISOString() }] }); throw error; }
}

export async function lifecycleDiagnostics({ database = dbDefault(), now = new Date() } = {}) {
  const [operations, jobs, projects, versions] = await Promise.all([database.collection(`organizations/${API_ORGANIZATION_ID}/recordLifecycleOperations`).get(), database.collection(`organizations/${API_ORGANIZATION_ID}/lifecyclePurgeJobs`).get(), database.collection(`organizations/${API_ORGANIZATION_ID}/projects`).get(), database.collectionGroup("versions").limit(500).get()]);
  const legacy = projects.docs.filter((doc) => !doc.data().lifecycle).map((doc) => ({ entityType: "project", entityId: doc.id })); const holds = projects.docs.filter((doc) => doc.data().lifecycle?.legalHold).map((doc) => ({ entityType: "project", entityId: doc.id })); const eligible = projects.docs.filter((doc) => doc.data().lifecycle?.purgeEligibleAt && Date.parse(doc.data().lifecycle.purgeEligibleAt) <= now.getTime() && !doc.data().lifecycle?.legalHold).map((doc) => ({ entityType: "project", entityId: doc.id }));
  const managedVersions = versions.docs.map((doc) => doc.data()).filter((version) => typeof version.storagePath === "string"); const expected = new Set(managedVersions.map((version) => version.storagePath)); let missingStorageObjects = []; let orphanedStorageObjects = []; let storageScanError = null;
  try { const bucket = getStorage(getAdminApp()).bucket(process.env.FIREBASE_STORAGE_BUCKET); for (const version of managedVersions) { const [exists] = await bucket.file(version.storagePath).exists(); if (!exists) missingStorageObjects.push({ documentId: version.documentId, versionId: version.id, storagePath: version.storagePath }); } const [files] = await bucket.getFiles({ prefix: `organizations/${API_ORGANIZATION_ID}/projects/`, maxResults: 500 }); orphanedStorageObjects = files.map((file) => file.name).filter((path) => !expected.has(path)).map((storagePath) => ({ storagePath })); } catch { storageScanError = "storage_inventory_unavailable"; }
  return { dryRun: true, generatedAt: now.toISOString(), operationCount: operations.size, operationCountsByType: operations.docs.reduce((counts, doc) => ({ ...counts, [doc.data().entityType]: (counts[doc.data().entityType] || 0) + 1 }), {}), failedOperations: operations.docs.filter((doc) => ["failed", "partially_applied"].includes(doc.data().status)).map((doc) => doc.data()), purgeJobs: jobs.docs.map((doc) => doc.data()), purgeEligibleRecords: eligible, legalHolds: holds, legacyRecordsWithoutLifecycle: legacy, missingStorageObjects, orphanedStorageObjects, storageScanError, retainedSnapshotDisclosure: "Operational purge retains immutable approved report and canonical export snapshots. Compliance erasure is a separate administrator process." };
}
