import { useEffect, useMemo, useState } from "react";
import type { ProjectPageProps } from "../App";
import { LifecycleStatusBadge, PurgeEligibilityNotice, RecordActionsMenu } from "../components/lifecycle/LifecycleComponents";
import { normalizeLifecycle } from "../lifecycle/policy";
import type { LifecycleEntityType, RecordLifecycleMetadata } from "../lifecycle/types";
import type { LifecycleOperation } from "../lifecycle/types";
import { listLifecycleOperations } from "../data/api";

type LifecycleRecord = { id: string; label: string; entityType: LifecycleEntityType; projectId: string; projectName: string; lifecycle?: RecordLifecycleMetadata };

export function LifecycleWorkspacePage({ projectState, role, userProfile, onLifecycleApplied = async () => undefined }: ProjectPageProps) {
  const [query, setQuery] = useState(""); const [state, setState] = useState("all"); const [entityType, setEntityType] = useState("all"); const [projectId, setProjectId] = useState("all");
  const [operations, setOperations] = useState<LifecycleOperation[]>([]);
  useEffect(() => { void listLifecycleOperations().then((result) => setOperations(result.operations)).catch(() => setOperations([])); }, []);
  const records = useMemo(() => {
    const projectName = (id: string) => projectState.projects.find((project) => project.id === id)?.name ?? "Project unavailable";
    const scoped = <T extends { id: string; projectId: string; lifecycle?: RecordLifecycleMetadata }>(items: T[], type: LifecycleEntityType, label: (item: T) => string) => items.map((item) => ({ id: item.id, label: label(item), entityType: type, projectId: item.projectId, projectName: projectName(item.projectId), lifecycle: item.lifecycle }));
    return [
      ...projectState.clients.map((item) => ({ id: item.id, label: item.name, entityType: "client" as const, projectId: "", projectName: "Organization", lifecycle: item.lifecycle })),
      ...projectState.projects.map((item) => ({ id: item.id, label: item.name, entityType: "project" as const, projectId: item.id, projectName: item.name, lifecycle: item.lifecycle })),
      ...scoped(projectState.phases, "phase", (item) => item.name), ...scoped(projectState.tasks, "task", (item) => item.title), ...scoped(projectState.taskDependencies.map((item) => ({ ...item, projectId: projectState.tasks.find((task) => task.id === item.taskId)?.projectId ?? "" })), "taskDependency", (item) => item.id),
      ...scoped(projectState.milestones, "milestone", (item) => item.name), ...scoped(projectState.risks, "risk", (item) => item.title), ...scoped(projectState.metrics, "metric", (item) => item.label), ...projectState.projectMembers.map((item) => ({ id: item.userId, label: projectState.users.find((user) => user.id === item.userId)?.name ?? item.userId, entityType: "projectMember" as const, projectId: item.projectId, projectName: projectName(item.projectId), lifecycle: item.lifecycle }))
    ].filter((record) => normalizeLifecycle(record.lifecycle).state !== "active");
  }, [projectState]);
  const managedProjectIds = new Set(role === "admin" ? projectState.projects.map((project) => project.id) : projectState.projects.filter((project) => project.ownerId === userProfile?.id || projectState.projectMembers.some((member) => member.projectId === project.id && member.userId === userProfile?.id && member.role === "lead")).map((project) => project.id));
  const visible = records.filter((record) => (managedProjectIds.has(record.projectId) || (role === "admin" && record.entityType === "client")) && (state === "all" || normalizeLifecycle(record.lifecycle).state === state) && (entityType === "all" || record.entityType === entityType) && (projectId === "all" || record.projectId === projectId) && `${record.label} ${record.projectName}`.toLowerCase().includes(query.toLowerCase()));
  if (!["admin", "project_manager"].includes(role) || managedProjectIds.size === 0) return <section className="panel"><h1>Records</h1><p>You do not have permission to view lifecycle records.</p></section>;
  return <section className="panel"><div className="panel-header"><div><h1>Archive &amp; Trash</h1><p>Restore retained operational records or review purge eligibility.</p></div></div><div className="lifecycle-filters"><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>State<select value={state} onChange={(event) => setState(event.target.value)}><option value="all">All retained states</option><option value="archived">Archived</option><option value="trashed">Trashed</option><option value="removed">Removed</option></select></label><label>Entity<select value={entityType} onChange={(event) => setEntityType(event.target.value)}><option value="all">All entities</option>{[...new Set(records.map((record) => record.entityType))].map((type) => <option key={type}>{type}</option>)}</select></label><label>Project<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="all">All projects</option>{projectState.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label></div><div className="trash-list">{visible.length ? visible.map((record) => { const history = operations.filter((operation) => operation.entityType === record.entityType && operation.entityId === record.id); return <article className="trash-list-row" key={`${record.entityType}-${record.id}`}><div><strong>{record.label}</strong><span>{record.entityType} · {record.projectName}</span><LifecycleStatusBadge lifecycle={record.lifecycle} />{history.length ? <details><summary>Operation history ({history.length})</summary>{history.map((operation) => <p key={operation.id}>{operation.action ?? (operation as LifecycleOperation & { requestedAction?: string }).requestedAction} · {operation.status} · {operation.actor.id ?? (operation as LifecycleOperation & { actorId?: string }).actorId}</p>)}</details> : null}</div><div><span>{record.lifecycle?.trashed?.at ?? record.lifecycle?.archived?.at ?? record.lifecycle?.removed?.at}</span><PurgeEligibilityNotice lifecycle={record.lifecycle} /></div><RecordActionsMenu actions={role === "admin" ? ["restore", "purge"] : ["restore"]} entityId={record.id} entityType={record.entityType} label={record.label} lifecycle={record.lifecycle} onApplied={onLifecycleApplied} projectId={record.projectId} projectRevision={projectState.projects.find((project) => project.id === record.projectId)?.revision ?? 1} role={role} /></article>; }) : <div className="table-empty">No lifecycle records match these filters.</div>}</div></section>;
}
